import { Project, ColorGradingParams, VideoClip, AudioClip, TextClip, TimelineTransition } from '../types';

export const createDefaultGrading = (): ColorGradingParams => ({
  brightness: 0,
  contrast: 0,
  saturation: 0,
  temperature: 0,
  tint: 0,
  vignette: 0,
  sharpness: 0,
  motionBlur: 0,
  lut: 'none',
  lift: { r: 0, g: 0, b: 0 },
  gamma: { r: 0, g: 0, b: 0 },
  gain: { r: 0, g: 0, b: 0 },
});

export const projectPresets: Project[] = [
  {
    id: 'template_1',
    name: 'Cyberpunk Tokyo Awakening',
    category: 'Cinematic',
    description: 'High-octane neon sci-fi cinematic sequence with cyberpunk color grading, glowing titles and synthwave soundtrack.',
    duration: 18,
    videoClips: [
      {
        id: 'v_1',
        name: 'Tokyo Neon Sequence (1.mp4)',
        type: 'video',
        proceduralType: 'cyberpunk_grid',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 25,
          saturation: 30,
          temperature: -10,
          tint: 15,
          vignette: 35,
          lut: 'cyberpunk',
        },
        volume: 100,
        videoUrl: '/1.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'cinema_glow',
        keyframes: [
          { id: 'kf1_1', time: 0, opacity: 0, scale: 105, positionX: 50, positionY: 50, rotation: 0 },
          { id: 'kf1_2', time: 1.5, opacity: 100, scale: 100, positionX: 50, positionY: 50, rotation: 0 },
        ],
      }
    ],
    audioClips: [
      {
        id: 'a_1',
        name: 'Cyber Synthwave Drive',
        type: 'audio',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        volume: 85,
        audioStyle: 'synth_wave',
      }
    ],
    textClips: [
      {
        id: 't_1',
        name: 'Cyberpunk Title',
        type: 'text',
        startTime: 1.0,
        duration: 5.0,
        text: 'NEO TOKYO 2099',
        color: '#00ffea',
        fontSize: 32,
        positionY: 45,
        style: 'neon',
        animation: 'glitch_shake',
      },
      {
        id: 't_1_sub',
        name: 'Subtitle',
        type: 'text',
        startTime: 6.5,
        duration: 4.5,
        text: 'DIRECTED BY PRO CREATOR',
        color: '#ff0099',
        fontSize: 18,
        positionY: 82,
        style: 'regular',
        animation: 'typewriter',
      }
    ],
    transitions: [],
    markers: [
      { id: 'm1', time: 1.0, color: '#00ffea', label: 'Title In' },
      { id: 'm2', time: 9.0, color: '#ff0099', label: 'Bass Drop' },
    ],
  },
  {
    id: 'template_2',
    name: 'Epic Mountain Expedition',
    category: 'Vlog',
    description: 'Breathtaking alpine travel exploration with warm golden hour tones, location badges, and atmospheric sound design.',
    duration: 16,
    videoClips: [
      {
        id: 'v_2',
        name: 'Alpine Ridge Drone (2.mp4)',
        type: 'video',
        proceduralType: 'vaporwave_sunset',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 15,
          saturation: 20,
          temperature: 25,
          vignette: 20,
          lut: 'warm_gold',
        },
        volume: 100,
        videoUrl: '/2.mp4',
        thumbnailUrl: '/bg2.png',
        aspectRatio: '2.39:1',
      }
    ],
    audioClips: [
      {
        id: 'a_2',
        name: 'Alpine Ambient Wind & Drone',
        type: 'audio',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        volume: 80,
        audioStyle: 'ambient_drone',
      }
    ],
    textClips: [
      {
        id: 't_2',
        name: 'Location Stamp',
        type: 'text',
        startTime: 1.2,
        duration: 6.0,
        text: 'SWISS ALPS • ELEVATION 3,454M',
        color: '#ffffff',
        fontSize: 22,
        positionY: 78,
        style: 'cinematic_lower_third',
        animation: 'fade_slide',
      }
    ],
    transitions: [],
    markers: [
      { id: 'm2_1', time: 1.2, color: '#f59e0b', label: 'Location Pin' },
      { id: 'm2_2', time: 8.0, color: '#38bdf8', label: 'Scenic Pan' },
    ],
  },
  {
    id: 'template_3',
    name: 'Neon Velocity Street Drift',
    category: 'Gaming',
    description: 'High-speed street car drifting and nighttime velocity with teal & orange grading, speed ramps and punchy bass.',
    duration: 15,
    videoClips: [
      {
        id: 'v_3',
        name: 'Speed Drift Sequence (3.mp4)',
        type: 'video',
        proceduralType: 'geometric_warp',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.2,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 30,
          saturation: 35,
          temperature: -15,
          vignette: 40,
          motionBlur: 20,
          lut: 'teal_orange',
        },
        volume: 100,
        videoUrl: '/3.mp4',
        thumbnailUrl: '/bg2.png',
        speedKeyframes: [
          { id: 'sk1', time: 0, speed: 1.0 },
          { id: 'sk2', time: 4.0, speed: 0.5 },
          { id: 'sk3', time: 7.0, speed: 2.0 },
          { id: 'sk4', time: 11.0, speed: 1.0 },
        ],
      }
    ],
    audioClips: [
      {
        id: 'a_3',
        name: 'High Octane Beats',
        type: 'audio',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        volume: 90,
        audioStyle: 'tech_house',
      }
    ],
    textClips: [
      {
        id: 't_3',
        name: 'Speed Title',
        type: 'text',
        startTime: 0.8,
        duration: 4.5,
        text: 'NIGHT RUN // ZERO LIMITS',
        color: '#ffff00',
        fontSize: 28,
        positionY: 50,
        style: 'glitch',
        animation: 'glitch_shake',
      }
    ],
    transitions: [],
    markers: [
      { id: 'm3_1', time: 4.0, color: '#ef4444', label: 'Slow Motion' },
      { id: 'm3_2', time: 7.0, color: '#10b981', label: 'Speed Boost' },
    ],
  },
  {
    id: 'template_4',
    name: 'Minimalist Tech Product Launch',
    category: 'Lifestyle',
    description: 'Clean studio presentation for modern hardware, luxury gadgets, and high-tech product commercial reels.',
    duration: 14,
    videoClips: [
      {
        id: 'v_4',
        name: 'Product Close-Up (4.mp4)',
        type: 'video',
        proceduralType: 'nebula_ocean',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 10,
          saturation: -5,
          brightness: 5,
          sharpness: 25,
          lut: 'vintage',
        },
        volume: 90,
        videoUrl: '/4.mp4',
        thumbnailUrl: '/bg2.png',
      }
    ],
    audioClips: [
      {
        id: 'a_4',
        name: 'Chill Tech Lofi',
        type: 'audio',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        volume: 70,
        audioStyle: 'lofi_chill',
      }
    ],
    textClips: [
      {
        id: 't_4',
        name: 'Brand Header',
        type: 'text',
        startTime: 1.0,
        duration: 5.0,
        text: 'PRO STUDIO EDITION',
        color: '#ffffff',
        fontSize: 26,
        positionY: 30,
        style: 'bordered',
        animation: 'typewriter',
      },
      {
        id: 't_4_badge',
        name: 'Feature Badge',
        type: 'text',
        startTime: 7.0,
        duration: 5.0,
        text: 'TITANIUM BUILD • 120HZ OLED',
        color: '#38bdf8',
        fontSize: 16,
        positionY: 80,
        style: 'badge',
        animation: 'fade_slide',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_5',
    name: 'Cinematic Golden Horizons',
    category: 'Cinematic',
    description: 'Sweeping anamorphic horizon views with dramatic film grain, deep shadows, and cinematic typography.',
    duration: 15,
    videoClips: [
      {
        id: 'v_5',
        name: 'Horizon Sunset (5.mp4)',
        type: 'video',
        proceduralType: 'vaporwave_sunset',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 20,
          saturation: 25,
          temperature: 30,
          vignette: 30,
          lut: 'warm_gold',
        },
        volume: 95,
        videoUrl: '/5.mp4',
        thumbnailUrl: '/bg2.png',
        aspectRatio: '2.39:1',
        effect: 'anamorphic',
      }
    ],
    audioClips: [
      {
        id: 'a_5',
        name: 'Majestic Cinematic Riser',
        type: 'audio',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        volume: 85,
        audioStyle: 'riser',
      }
    ],
    textClips: [
      {
        id: 't_5',
        name: 'Cinematic Opener',
        type: 'text',
        startTime: 1.5,
        duration: 6.0,
        text: 'BEYOND HORIZONS',
        color: '#ffffff',
        fontSize: 34,
        positionY: 50,
        style: 'regular',
        animation: 'fade_slide',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_6',
    name: 'Urban Streetwear & Culture',
    category: 'Lifestyle',
    description: 'Dynamic fashion lookbook featuring fast cuts, vivid street colors, VHS vintage filters, and pop titles.',
    duration: 14,
    videoClips: [
      {
        id: 'v_6',
        name: 'Street Fashion (6.mp4)',
        type: 'video',
        proceduralType: 'cyberpunk_grid',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 20,
          saturation: 30,
          vignette: 15,
          lut: 'vintage',
        },
        volume: 90,
        videoUrl: '/6.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'vhs',
      }
    ],
    audioClips: [
      {
        id: 'a_6',
        name: 'Street Beat Rhythm',
        type: 'audio',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        volume: 85,
        audioStyle: 'beat_loop',
      }
    ],
    textClips: [
      {
        id: 't_6',
        name: 'Streetwear Brand',
        type: 'text',
        startTime: 1.0,
        duration: 4.5,
        text: 'AUTUMN / WINTER 2026',
        color: '#ff0099',
        fontSize: 26,
        positionY: 25,
        style: 'neon',
        animation: 'bounce',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_7',
    name: 'Content Creator Masterclass',
    category: 'Vlog',
    description: 'Polished studio talking head & tutorial edit with crystal-clear color grading, dynamic lower thirds and B-roll sync.',
    duration: 16,
    videoClips: [
      {
        id: 'v_7',
        name: 'Studio Vlog (7.mp4)',
        type: 'video',
        proceduralType: 'nebula_ocean',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          brightness: 5,
          contrast: 15,
          saturation: 10,
          temperature: 5,
          sharpness: 20,
          lut: 'none',
        },
        volume: 100,
        videoUrl: '/7.mp4',
        thumbnailUrl: '/bg2.png',
      }
    ],
    audioClips: [
      {
        id: 'a_7',
        name: 'Lo-Fi Background Music',
        type: 'audio',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        volume: 60,
        audioStyle: 'lofi_chill',
      }
    ],
    textClips: [
      {
        id: 't_7',
        name: 'Host Name Tag',
        type: 'text',
        startTime: 1.0,
        duration: 5.5,
        text: 'ALEX RIVERA • CREATIVE DIRECTOR',
        color: '#00ffea',
        fontSize: 20,
        positionY: 82,
        style: 'cinematic_lower_third',
        animation: 'fade_slide',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_8',
    name: 'Extreme Sports Action Showcase',
    category: 'Gaming',
    description: 'Adrenaline-packed motion edit with intense color grade, motion blur enhancement, and dramatic speed cuts.',
    duration: 18,
    videoClips: [
      {
        id: 'v_8',
        name: 'Action Showcase (8.mp4)',
        type: 'video',
        proceduralType: 'geometric_warp',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 30,
          saturation: 40,
          vignette: 35,
          motionBlur: 30,
          lut: 'teal_orange',
        },
        volume: 100,
        videoUrl: '/8.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'rgb_split',
      }
    ],
    audioClips: [
      {
        id: 'a_8',
        name: 'Heavy 808 Bass Line',
        type: 'audio',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        volume: 95,
        audioStyle: '808_bass',
      }
    ],
    textClips: [
      {
        id: 't_8',
        name: 'Impact Title',
        type: 'text',
        startTime: 0.5,
        duration: 4.0,
        text: 'MAXIMUM ADRENALINE',
        color: '#ff0055',
        fontSize: 32,
        positionY: 50,
        style: 'glitch',
        animation: 'glitch_shake',
      }
    ],
    transitions: [],
    markers: [
      { id: 'm8_1', time: 6.0, color: '#ff0055', label: 'Drop In' },
      { id: 'm8_2', time: 12.0, color: '#00ffea', label: 'Apex Turn' },
    ],
  },
  {
    id: 'template_9',
    name: 'Retro 80s Synthwave Aesthetic',
    category: 'Cinematic',
    description: 'Nostalgic retro wave universe with CRT scanlines, chromatic aberration, neon purple palettes, and vintage audio.',
    duration: 15,
    videoClips: [
      {
        id: 'v_9',
        name: 'Retro Aesthetic (9.mp4)',
        type: 'video',
        proceduralType: 'vaporwave_sunset',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 25,
          saturation: 45,
          tint: 30,
          vignette: 45,
          lut: 'cyberpunk',
        },
        volume: 90,
        videoUrl: '/9.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'vhs',
      }
    ],
    audioClips: [
      {
        id: 'a_9',
        name: 'Vintage Synth Chords',
        type: 'audio',
        startTime: 0,
        duration: 15,
        sourceStart: 0,
        volume: 85,
        audioStyle: 'synth_wave',
      }
    ],
    textClips: [
      {
        id: 't_9',
        name: 'Retro Title',
        type: 'text',
        startTime: 1.0,
        duration: 5.0,
        text: 'SYNTH MEMORIES 1984',
        color: '#ff00cc',
        fontSize: 28,
        positionY: 45,
        style: 'neon',
        animation: 'neon_pulse',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_10',
    name: 'Film Noir Documentary Story',
    category: 'Cinematic',
    description: 'High-contrast monochrome film noir aesthetic with authentic silver-halide grain and poetic title typography.',
    duration: 16,
    videoClips: [
      {
        id: 'v_10',
        name: 'Film Noir Scene (10.mp4)',
        type: 'video',
        proceduralType: 'nebula_ocean',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 40,
          brightness: -5,
          vignette: 50,
          sharpness: 30,
          lut: 'monochrome',
        },
        volume: 85,
        videoUrl: '/10.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'film_grain',
        aspectRatio: '4:3',
      }
    ],
    audioClips: [
      {
        id: 'a_10',
        name: 'Cinematic Mystery Ambient',
        type: 'audio',
        startTime: 0,
        duration: 16,
        sourceStart: 0,
        volume: 75,
        audioStyle: 'ambient_drone',
      }
    ],
    textClips: [
      {
        id: 't_10',
        name: 'Noir Title',
        type: 'text',
        startTime: 1.5,
        duration: 5.5,
        text: 'CHAPTER X • THE UNSEEN',
        color: '#ffffff',
        fontSize: 24,
        positionY: 75,
        style: 'bordered',
        animation: 'fade_slide',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_11',
    name: 'Metropolis City Hyperlapse',
    category: 'Vlog',
    description: 'High-speed urban traffic and architectural hyperlapse with vibrant daylight grading and modern dynamic badges.',
    duration: 14,
    videoClips: [
      {
        id: 'v_11',
        name: 'City Hyperlapse (11.mp4)',
        type: 'video',
        proceduralType: 'geometric_warp',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.5,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 20,
          saturation: 25,
          sharpness: 30,
          lut: 'warm_gold',
        },
        volume: 90,
        videoUrl: '/11.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'bloom',
      }
    ],
    audioClips: [
      {
        id: 'a_11',
        name: 'Urban Pulse Beat',
        type: 'audio',
        startTime: 0,
        duration: 14,
        sourceStart: 0,
        volume: 85,
        audioStyle: 'tech_house',
      }
    ],
    textClips: [
      {
        id: 't_11',
        name: 'City Tag',
        type: 'text',
        startTime: 1.0,
        duration: 4.5,
        text: 'METROPOLIS IN MOTION',
        color: '#00ffea',
        fontSize: 26,
        positionY: 35,
        style: 'neon',
        animation: 'typewriter',
      }
    ],
    transitions: [],
    markers: [],
  },
  {
    id: 'template_12',
    name: 'Cosmic Deep Space Voyage',
    category: 'Cinematic',
    description: 'Interstellar planetary journey with deep space nebulas, glowing starry auras, futuristic title cards and ambient sound.',
    duration: 18,
    videoClips: [
      {
        id: 'v_12',
        name: 'Deep Cosmos (12.mp4)',
        type: 'video',
        proceduralType: 'nebula_ocean',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        sourceDuration: 30,
        speed: 1.0,
        colorGrading: {
          ...createDefaultGrading(),
          contrast: 30,
          saturation: 35,
          temperature: -20,
          vignette: 45,
          lut: 'cyberpunk',
        },
        volume: 95,
        videoUrl: '/12.mp4',
        thumbnailUrl: '/bg2.png',
        effect: 'cinema_glow',
      }
    ],
    audioClips: [
      {
        id: 'a_12',
        name: 'Deep Space Drone',
        type: 'audio',
        startTime: 0,
        duration: 18,
        sourceStart: 0,
        volume: 80,
        audioStyle: 'ambient_drone',
      }
    ],
    textClips: [
      {
        id: 't_12',
        name: 'Space Title',
        type: 'text',
        startTime: 1.2,
        duration: 6.0,
        text: 'INTERSTELLAR // ODYSSEY',
        color: '#c084fc',
        fontSize: 30,
        positionY: 50,
        style: 'neon',
        animation: 'glitch_shake',
      }
    ],
    transitions: [],
    markers: [
      { id: 'm12_1', time: 1.2, color: '#c084fc', label: 'Warp In' },
      { id: 'm12_2', time: 10.0, color: '#38bdf8', label: 'Orbital Insertion' },
    ],
  }
];
